#import "@preview/touying:0.6.1": *
#import themes.stargazer: *
#import "@preview/timeliney:0.2.1"
#import "../../custom.typ": *

= About the course

== What is Artificial Intelligence?

#dblock(title: [Artificial Intelligence])[
  Field of research that studies how to build computational systems capable of performing tasks associated with human intelligence, such as perceiving, reasoning, learning, and acting.
]

It follows four historic approaches (Russell & Norvig, 2010):
- Thinking Humanly: Think cognitively the way humans do.
- Thinking Rationally: Derive correct solutions from formal logic.
- Acting Humanly: Behave like humans in conversation and action (Turing Test approach).
- Acting Rationally: Choose actions to achieve the best expected outcome.

== How does AI relates to the Web?
#place(top + left, dx: -2.5em)[
  #subbar([Web Intelligence])
]

#dblock(title: [Web Intelligence])[
  Area of study and research of the application of *Artificial Intelligence* and *Information Technology* on the Web, in order to create the next generation of products, services and frameworks based on the internet.
]

It covers the fields like:
- Web Mining
- Information Retrieval
- Semantic Web
- Intelligent Agents
- Adaptive Web Sites

== Core concepts

#place(top + left, dx: -2.5em)[
  #subbar([Web Mining])
]

#dblock(title: [Web Mining])[
  Application of *Data Mining* techniques to discover patterns from the web data.
]

It can be divided into three categories:

- Web Content Mining
- Web Structure Mining
- Web Usage Mining

== Core concepts

#place(top + left, dx: -2.5em)[
  #subbar([Web Mining])
]

The data in the Web:

- A really huge collection
- Heterogeneous and Unclassified
- Time variable
- Semi-structured
- Highly Dimensional

#block(
  width: 100%,
  height: auto,
  fill:luma(230),
  inset: 8pt, 
  radius: 4pt,
  text()[_The Web is considered the world biggest open and democratic publication system. _#footnote[J. D. Velásquez and V. Palade. Adaptive Web Sites (2008)]]
)

== Core concepts

#place(top + left, dx: -2.5em)[
  #subbar([Intelligent Agents])
]

#dblock(title: [Intelligent Agents])[
  Computer systems that are situated in an environment and are capable of *flexible autonomous action* in order to pursue a goal.
]

A key concept in agents is autonomy, the can *act independently of human intervention* to reach a design objective.

== What can we use AI applied to the Web for?
#place(top + left, dx: -2.5em)[
  #subbar([Understand web content])
]
#v(20pt)
#figure(image("images/content.png", height: 90%))

== What can we use AI applied to the Web for?
#place(top + left, dx: -2.5em)[
  #subbar([Understand web structure])
]
#v(20pt)
#figure(image("images/structure.png", height: 90%))

== What can we use AI applied to the Web for?
#place(top + left, dx: -2.5em)[
  #subbar([Understand web user behaviour])
]
#v(20pt)
#figure(image("images/usage.png", height: 90%))

== What can we use AI applied to the Web for?
#place(top + left, dx: -2.5em)[
  #subbar([Build intelligent agents])
]
#v(20pt)
#figure(image("images/agent.png", height: 90%))

== Course Outline
#place(top + left, dx: -2.5em)[
  #subbar([Chapters])
]

1. Fundamentals of AI applied to the Web

2. Web Content Mining

3. Web Structure Mining

4. Web Usage Mining

5. Intelligent Agents on the Web

6. Human-Computer Interaction and Intelligent Interfaces


== Course Outline

#dblock(title: [Fundamentals of AI applied to the Web])[
  Some initial concepts to the area, describing the basic taxonomy of Web Mining and some practical uses of its components and recap of Data Mining and Machine Learning topics.
]

#dblock(title: [Web Content Mining])[
  We will define the main web contents that we can find (mainly text), how we can retrieve them and how we can use it to describe and compare between web pages in a theoretical and practical way.
]

== Course Outline

#dblock(title: [Web Structure Mining])[
  We will describe how we can characterize the structure of the web, what is the value behind it and some tools to achieve it. Of course, we will review some practical uses and applications that are part of the state of the art in this topic.
]

#dblock(title: [Web Usage Mining])[
  We will characteize the use of the web from two points of view. One from the _records_ generated by its use and another from the _content_ generated by its use. It will be described what we can do with these characterizations, practical uses and some tool to apply it.
]


== Course Outline

#dblock(title: [Intelligent Agents on the Web])[
  We will learn the fundamentals of intelligent agents and their application on the Web. We will explore agent architectures based on large language models (LLMs) and use frameworks and apply these tool to solve real-world problems.
]

#dblock(title: [Human-Computer Interaction and Intelligent Interfaces])[
  We will focus on the design and evaluation of adaptive and conversational interfaces for web-based problems.
]

== Learning Outcome

#place(top + left, dx: -2.5em)[
  #subbar([What you'll be able to do?])
]

By the end of this course, you will be able to:

- Frame real-world web problems and select AI-appropriate approaches.
- Design and implement an AI solution for the web, end-to-end.
- Evaluate your solution and communicate results clearly.

= Teaching team
== Professors

#{
  set par(leading: 0.5em)
  set text(size: 15pt)
  
  grid(
    columns: (33%, 34%, 33%,),
    rows:(auto, auto),
    align: center,
    box(
      clip: true,
      radius: 5cm,
      width: 6cm,
      height: 6cm,
      image("images/jv.jpg")
    ),
    box(
      clip: true,
      radius: 5cm,
      width: 6cm,
      height: 6cm,
      image("images/dc.jpg")
    ),
    box(
      clip: true,
      radius: 5cm,
      width: 6cm,
      height: 6cm,
      image("images/fh.jpeg")
    ),
    par()[\
      *Juan D. Velásquez* \
      PhD. University of Tokyo \
      Profesor Titular \
      Universidad de Chile \
    ],
    par()[\
      *Diego Cornejo* \
      Tesista MsC Data Science \
      Ing. Civil Industrial \
      Universidad de Chile \
    ],
    par()[\
      *Felipe Hernández* \
      Tesista MsC Data Science \
      Ing. Industrial y en Computación \
      Universidad de Chile \
    ],
  )
}

== Teaching Assistant

#{
  set par(leading: 0.5em)
  set text(size: 15pt)
  
  grid(
    columns: (100%,),
    rows:(auto, auto),
    align: center,
    box(
      clip: true,
      radius: 5cm,
      width: 6cm,
      height: 6cm,
      image("images/fs.jpg")
    ),
    par()[\
      *Fernanda Saavedra* \
      Profesora Auxiliar \
      Tesista MsC Data Science \
      Universidad de Chile \
    ],
  )
}

= Game rules

== Tools

- *Python*: One of the most popular programming language for Data Science.

- *Jupyter Notebook*: Web application for the creation and sharing of _computational docuemnts_, that could include markup text, code, and visualization tools.
#block(
  width: 100%,
  height: 10%,
  fill:luma(190),
  inset: 8pt, 
  radius: 4pt,
  text()[*Assumptions*]
)
#v(-1.4em)
#block(
  width: 100%,
  height: auto,
  fill:luma(240),
  inset: 8pt, 
  radius: 0pt,
  text()[
    - This course assumes that students have no prior knowledge about Web Intelligence and its practical uses and Jupyter Notebook usage.

    - This course assumes minimum knowledge about Python programming, Data Mining and Machine Learning.
  ]
)


== Evaluations

*Controles (3):*
- Control 1: Semana 6
- Control 2: Semana 11
- Control 3: Semana 14

*Tareas Grupales (4):*
- Tarea 1: 20/08/2025 - 24/09/2025
- Tarea 2: 24/09/2025 - 15/10/2025
- Tarea 3: 15/10/2025 - 12/11/2025
- Tarea 4: 12/11/2025 - 03/12/2025

#align(center,
  block(
    width: 100%,
    height: 10%,
    fill:luma(190),
    inset: 8pt, 
    radius: 4pt,
    [*No hay examen*]
  )
)


== Evaluations

- *Nota de Control (NC)*
  - $"if" C_(1), C_(2), C_(3) >= 4.0 -> "NC" = frac("Max"(C_(1) + C_(2) + C_(3)), 3) + frac("2ndBest"(C_(1) + C_(2) + C_(3)) times 2, 3)$
  - $"else" -> "NC" = frac(C_(1) + C_(2) + C_(3), 3)$

- *Nota Tareas (NT)*
  - $"NT" = frac(T_(1) + T_(2) + T_(3) + T_(4), 4)$

- *Criterio de Aprobación:*
  - $"NC" >= 4.0$
  - $"NT" > 4.0$

- *Nota Final (NF)*
  - $"NF" = 50% times "NC" + 50% times "NT"$

== Working Groups

- Grupos de 3 miembros (ustedes los eligen).

- Coevaluaciones por tarea:
  - Cada tarea $i$ tendra una nota de coevaluación $V_i$, que corresponde al promedio de las notas asignadas por sus pares.
  - Si $V_i >= 5.0$, su nota en la tarea $i$ es la asignada por el ayudante $T_i$.
  - Si $V_i < 5.0$, su nota en la tarea $i$ será $V_i$.